import { useState } from "react";
import { ToolCard } from "./ToolCard";
import { Dropzone } from "./Dropzone";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Brain, FileMusic, Layers, Sparkles, Download, Youtube } from "lucide-react";
import { toast } from "sonner";
import { useProcessingTask } from "./useProcessingTask";
import { ProcessingPanel } from "./ProcessingPanel";

const KEYS = ["Am", "C", "G", "Em", "F", "Dm", "A", "E"];
const PROGRESSIONS = [
  ["Am", "F", "C", "G"],
  ["C", "G", "Am", "F"],
  ["Dm", "Bb", "F", "C"],
  ["Em", "C", "G", "D"],
];
const pick = <T,>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];
const rand = (min: number, max: number) => Math.floor(min + Math.random() * (max - min));

function dummyDownload(name: string): { bytes: BlobPart; filename: string; mime: string } {
  return {
    bytes: `# ${name}\nGenerated by Musician Tools — ${new Date().toISOString()}\n`,
    filename: name,
    mime: "text/plain",
  };
}

export function AnalysisCategory() {
  const [stems, setStems] = useState({ vocals: true, drums: false, bass: false, denoise: false });
  const [ytUrl, setYtUrl] = useState("");

  const analyzer = useProcessingTask();
  const sheetMusic = useProcessingTask();
  const splitter = useProcessingTask();
  const progGen = useProcessingTask();

  const handleFile = (cb: (f: File) => void) => (files: File[]) => {
    if (files[0]) {
      toast.success("הקובץ הועלה בהצלחה");
      cb(files[0]);
    }
  };

  return (
    <div className="grid gap-4 md:grid-cols-2">
      <ToolCard title="Smart Analyzer" description="זיהוי אקורדים וסולם" icon={<Brain className="h-5 w-5" />} badge="AI">
        <div className="space-y-2">
          <Label className="text-xs">קישור YouTube</Label>
          <div className="flex gap-2">
            <div className="relative flex-1">
              <Youtube className="absolute right-2 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                dir="ltr"
                placeholder="https://youtube.com/..."
                className="pr-8"
                value={ytUrl}
                onChange={(e) => setYtUrl(e.target.value)}
              />
            </div>
            <Button
              onClick={() => {
                if (!ytUrl) return toast.error("הדבק קישור YouTube");
                analyzer.run("ניתוח", () => {
                  const key = pick(KEYS);
                  const prog = pick(PROGRESSIONS).join(" → ");
                  return {
                    data: { "סולם": key, BPM: rand(70, 140), "אקורדים": prog },
                    download: dummyDownload("analysis.txt"),
                  };
                });
              }}
            >
              נתח
            </Button>
          </div>
          <div className="text-center text-[11px] text-muted-foreground">— או —</div>
          <Dropzone hint="העלה קובץ אודיו לניתוח" onFiles={handleFile(() => {
            analyzer.run("ניתוח", () => ({
              data: { "סולם": pick(KEYS), BPM: rand(70, 140), "אקורדים": pick(PROGRESSIONS).join(" → ") },
              download: dummyDownload("analysis.txt"),
            }));
          })} />
        </div>
        <ProcessingPanel {...analyzer} onDownload={analyzer.download} onReset={analyzer.reset} />
      </ToolCard>

      <ToolCard title="גנרטור תווים" description="המרת אודיו לתווים" icon={<FileMusic className="h-5 w-5" />}>
        <Dropzone hint="העלה אודיו ליצירת תווים" onFiles={handleFile(() => {
          sheetMusic.run("יצירת תווים", () => ({
            data: { "סולם": pick(KEYS), "תיבות": rand(16, 64), "כלי": "פסנתר" },
            download: dummyDownload("sheet-music.pdf"),
          }), 4000);
        })} />
        <div className="mt-3 grid grid-cols-2 gap-2">
          <div>
            <Label className="text-xs">סולם</Label>
            <Select defaultValue="auto">
              <SelectTrigger className="h-9"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="auto">זיהוי אוטומטי</SelectItem>
                <SelectItem value="c-major">דו מז'ור</SelectItem>
                <SelectItem value="a-minor">לה מינור</SelectItem>
                <SelectItem value="g-major">סול מז'ור</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label className="text-xs">כלי</Label>
            <Select defaultValue="piano">
              <SelectTrigger className="h-9"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="piano">פסנתר</SelectItem>
                <SelectItem value="guitar">גיטרה</SelectItem>
                <SelectItem value="violin">כינור</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <ProcessingPanel {...sheetMusic} onDownload={sheetMusic.download} onReset={sheetMusic.reset} />
      </ToolCard>

      <ToolCard title="Stem Splitter & Denoise" description="הפרדת ערוצים והפחתת רעש" icon={<Layers className="h-5 w-5" />} badge="AI">
        <Dropzone hint="העלה אודיו לפיצול" onFiles={handleFile(() => {
          const active = Object.entries(stems).filter(([, v]) => v).map(([k]) => k);
          splitter.run("פיצול ערוצים", () => ({
            data: { "ערוצים שחולצו": active.length, "איכות": "320kbps" },
            download: dummyDownload("stems.zip"),
          }), 5000);
        })} />
        <div className="mt-3 space-y-2">
          {[
            { key: "vocals", label: "חילוץ ווקאל" },
            { key: "drums", label: "חילוץ תופים" },
            { key: "bass", label: "חילוץ באס" },
            { key: "denoise", label: "ניקוי רעשי רקע" },
          ].map((o) => (
            <div key={o.key} className="flex items-center justify-between rounded-md border bg-card/50 px-3 py-2">
              <Label className="text-sm">{o.label}</Label>
              <Switch
                checked={stems[o.key as keyof typeof stems]}
                onCheckedChange={(v) => setStems((p) => ({ ...p, [o.key]: v }))}
              />
            </div>
          ))}
        </div>
        <ProcessingPanel {...splitter} onDownload={splitter.download} onReset={splitter.reset} />
      </ToolCard>

      <ToolCard title="AI Chord Progression" description="יצירת פרוגרסיית אקורדים" icon={<Sparkles className="h-5 w-5" />} badge="AI">
        <div className="grid grid-cols-2 gap-2">
          <div>
            <Label className="text-xs">מצב רוח</Label>
            <Select defaultValue="happy">
              <SelectTrigger className="h-9"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="happy">שמח</SelectItem>
                <SelectItem value="sad">עצוב</SelectItem>
                <SelectItem value="epic">אפי</SelectItem>
                <SelectItem value="chill">רגוע</SelectItem>
                <SelectItem value="tense">מתוח</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label className="text-xs">סולם</Label>
            <Select defaultValue="c-major">
              <SelectTrigger className="h-9"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="c-major">דו מז'ור</SelectItem>
                <SelectItem value="a-minor">לה מינור</SelectItem>
                <SelectItem value="d-dorian">רה דוריאן</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="mt-3 flex flex-wrap gap-2">
          {(progGen.result?.data?.["אקורדים"] as string | undefined)?.split(" → ").map((c, i) => (
            <div key={i} className="flex h-14 w-14 items-center justify-center rounded-lg border bg-primary/10 font-mono text-sm font-bold text-primary">
              {c}
            </div>
          )) || ["I", "vi", "IV", "V"].map((c) => (
            <div key={c} className="flex h-14 w-14 items-center justify-center rounded-lg border bg-primary/5 font-mono text-lg font-bold text-primary">
              {c}
            </div>
          ))}
        </div>
        <div className="mt-3 grid grid-cols-2 gap-2">
          <Button variant="outline" onClick={() => progGen.run("יצירת פרוגרסיה", () => ({
            data: { "אקורדים": pick(PROGRESSIONS).join(" → "), "מפתח": pick(KEYS) },
            download: dummyDownload("progression.mid"),
          }), 2500)}>צור מחדש</Button>
          <Button onClick={progGen.download} disabled={!progGen.result?.download}>
            <Download className="ml-2 h-4 w-4" /> הורד MIDI
          </Button>
        </div>
        <ProcessingPanel {...progGen} onDownload={progGen.download} onReset={progGen.reset} />
      </ToolCard>
    </div>
  );
}
