/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProsRouteImport } from './routes/pros'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ProsIndexRouteImport } from './routes/pros.index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as ShopCheckoutRouteImport } from './routes/shop.checkout'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as SellerSellerIdRouteImport } from './routes/seller.$sellerId'
import { Route as ProsNewRouteImport } from './routes/pros.new'
import { Route as ProsMyInquiriesRouteImport } from './routes/pros.my-inquiries'
import { Route as ProsProIdRouteImport } from './routes/pros.$proId'
import { Route as MarketplaceNewRouteImport } from './routes/marketplace.new'
import { Route as MarketplaceListingIdRouteImport } from './routes/marketplace.$listingId'
import { Route as AcademyPodcastsRouteImport } from './routes/academy.podcasts'
import { Route as AcademySlugRouteImport } from './routes/academy.$slug'
import { Route as ShopOrderOrderIdRouteImport } from './routes/shop.order.$orderId'
import { Route as ProsProIdEditRouteImport } from './routes/pros.$proId.edit'
import { Route as MarketplaceCategorySlugRouteImport } from './routes/marketplace.category.$slug'
import { Route as MarketplaceListingIdEditRouteImport } from './routes/marketplace.$listingId.edit'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin.customers.$customerId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicMarketplaceMatchSearchesRouteImport } from './routes/api/public/marketplace.match-searches'
import { Route as ApiPublicMarketplaceFollowupRouteImport } from './routes/api/public/marketplace.followup'
import { Route as ApiPublicMarketplaceAutoBumpRouteImport } from './routes/api/public/marketplace.auto-bump'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsRoute = ProsRouteImport.update({
  id: '/pros',
  path: '/pros',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ProsIndexRoute = ProsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProsRoute,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const SellerSellerIdRoute = SellerSellerIdRouteImport.update({
  id: '/seller/$sellerId',
  path: '/seller/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsNewRoute = ProsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProsRoute,
} as any)
const ProsMyInquiriesRoute = ProsMyInquiriesRouteImport.update({
  id: '/my-inquiries',
  path: '/my-inquiries',
  getParentRoute: () => ProsRoute,
} as any)
const ProsProIdRoute = ProsProIdRouteImport.update({
  id: '/$proId',
  path: '/$proId',
  getParentRoute: () => ProsRoute,
} as any)
const MarketplaceNewRoute = MarketplaceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceListingIdRoute = MarketplaceListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AcademyPodcastsRoute = AcademyPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const ShopOrderOrderIdRoute = ShopOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => ShopRoute,
} as any)
const ProsProIdEditRoute = ProsProIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProsProIdRoute,
} as any)
const MarketplaceCategorySlugRoute = MarketplaceCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceListingIdEditRoute =
  MarketplaceListingIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MarketplaceListingIdRoute,
  } as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarketplaceMatchSearchesRoute =
  ApiPublicMarketplaceMatchSearchesRouteImport.update({
    id: '/api/public/marketplace/match-searches',
    path: '/api/public/marketplace/match-searches',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarketplaceFollowupRoute =
  ApiPublicMarketplaceFollowupRouteImport.update({
    id: '/api/public/marketplace/followup',
    path: '/api/public/marketplace/followup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarketplaceAutoBumpRoute =
  ApiPublicMarketplaceAutoBumpRouteImport.update({
    id: '/api/public/marketplace/auto-bump',
    path: '/api/public/marketplace/auto-bump',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forum': typeof ForumRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/profile': typeof ProfileRoute
  '/pros': typeof ProsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/shorts': typeof ShortsRoute
  '/store': typeof StoreRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/academy/podcasts': typeof AcademyPodcastsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRouteWithChildren
  '/marketplace/new': typeof MarketplaceNewRoute
  '/pros/$proId': typeof ProsProIdRouteWithChildren
  '/pros/my-inquiries': typeof ProsMyInquiriesRoute
  '/pros/new': typeof ProsNewRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/pros/': typeof ProsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/marketplace/$listingId/edit': typeof MarketplaceListingIdEditRoute
  '/marketplace/category/$slug': typeof MarketplaceCategorySlugRoute
  '/pros/$proId/edit': typeof ProsProIdEditRoute
  '/shop/order/$orderId': typeof ShopOrderOrderIdRoute
  '/api/public/marketplace/auto-bump': typeof ApiPublicMarketplaceAutoBumpRoute
  '/api/public/marketplace/followup': typeof ApiPublicMarketplaceFollowupRoute
  '/api/public/marketplace/match-searches': typeof ApiPublicMarketplaceMatchSearchesRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forum': typeof ForumRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shorts': typeof ShortsRoute
  '/store': typeof StoreRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/academy/podcasts': typeof AcademyPodcastsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRouteWithChildren
  '/marketplace/new': typeof MarketplaceNewRoute
  '/pros/$proId': typeof ProsProIdRouteWithChildren
  '/pros/my-inquiries': typeof ProsMyInquiriesRoute
  '/pros/new': typeof ProsNewRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/pros': typeof ProsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/marketplace/$listingId/edit': typeof MarketplaceListingIdEditRoute
  '/marketplace/category/$slug': typeof MarketplaceCategorySlugRoute
  '/pros/$proId/edit': typeof ProsProIdEditRoute
  '/shop/order/$orderId': typeof ShopOrderOrderIdRoute
  '/api/public/marketplace/auto-bump': typeof ApiPublicMarketplaceAutoBumpRoute
  '/api/public/marketplace/followup': typeof ApiPublicMarketplaceFollowupRoute
  '/api/public/marketplace/match-searches': typeof ApiPublicMarketplaceMatchSearchesRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forum': typeof ForumRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/profile': typeof ProfileRoute
  '/pros': typeof ProsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/shorts': typeof ShortsRoute
  '/store': typeof StoreRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/academy/podcasts': typeof AcademyPodcastsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRouteWithChildren
  '/marketplace/new': typeof MarketplaceNewRoute
  '/pros/$proId': typeof ProsProIdRouteWithChildren
  '/pros/my-inquiries': typeof ProsMyInquiriesRoute
  '/pros/new': typeof ProsNewRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/pros/': typeof ProsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/marketplace/$listingId/edit': typeof MarketplaceListingIdEditRoute
  '/marketplace/category/$slug': typeof MarketplaceCategorySlugRoute
  '/pros/$proId/edit': typeof ProsProIdEditRoute
  '/shop/order/$orderId': typeof ShopOrderOrderIdRoute
  '/api/public/marketplace/auto-bump': typeof ApiPublicMarketplaceAutoBumpRoute
  '/api/public/marketplace/followup': typeof ApiPublicMarketplaceFollowupRoute
  '/api/public/marketplace/match-searches': typeof ApiPublicMarketplaceMatchSearchesRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/forum'
    | '/marketplace'
    | '/profile'
    | '/pros'
    | '/reset-password'
    | '/shop'
    | '/shorts'
    | '/store'
    | '/academy/$slug'
    | '/academy/podcasts'
    | '/marketplace/$listingId'
    | '/marketplace/new'
    | '/pros/$proId'
    | '/pros/my-inquiries'
    | '/pros/new'
    | '/seller/$sellerId'
    | '/shop/$slug'
    | '/shop/checkout'
    | '/verify/$code'
    | '/marketplace/'
    | '/pros/'
    | '/shop/'
    | '/admin/customers/$customerId'
    | '/marketplace/$listingId/edit'
    | '/marketplace/category/$slug'
    | '/pros/$proId/edit'
    | '/shop/order/$orderId'
    | '/api/public/marketplace/auto-bump'
    | '/api/public/marketplace/followup'
    | '/api/public/marketplace/match-searches'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/forum'
    | '/profile'
    | '/reset-password'
    | '/shorts'
    | '/store'
    | '/academy/$slug'
    | '/academy/podcasts'
    | '/marketplace/$listingId'
    | '/marketplace/new'
    | '/pros/$proId'
    | '/pros/my-inquiries'
    | '/pros/new'
    | '/seller/$sellerId'
    | '/shop/$slug'
    | '/shop/checkout'
    | '/verify/$code'
    | '/marketplace'
    | '/pros'
    | '/shop'
    | '/admin/customers/$customerId'
    | '/marketplace/$listingId/edit'
    | '/marketplace/category/$slug'
    | '/pros/$proId/edit'
    | '/shop/order/$orderId'
    | '/api/public/marketplace/auto-bump'
    | '/api/public/marketplace/followup'
    | '/api/public/marketplace/match-searches'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/forum'
    | '/marketplace'
    | '/profile'
    | '/pros'
    | '/reset-password'
    | '/shop'
    | '/shorts'
    | '/store'
    | '/academy/$slug'
    | '/academy/podcasts'
    | '/marketplace/$listingId'
    | '/marketplace/new'
    | '/pros/$proId'
    | '/pros/my-inquiries'
    | '/pros/new'
    | '/seller/$sellerId'
    | '/shop/$slug'
    | '/shop/checkout'
    | '/verify/$code'
    | '/marketplace/'
    | '/pros/'
    | '/shop/'
    | '/admin/customers/$customerId'
    | '/marketplace/$listingId/edit'
    | '/marketplace/category/$slug'
    | '/pros/$proId/edit'
    | '/shop/order/$orderId'
    | '/api/public/marketplace/auto-bump'
    | '/api/public/marketplace/followup'
    | '/api/public/marketplace/match-searches'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ForumRoute: typeof ForumRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ProsRoute: typeof ProsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRouteWithChildren
  ShortsRoute: typeof ShortsRoute
  StoreRoute: typeof StoreRoute
  SellerSellerIdRoute: typeof SellerSellerIdRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  ApiPublicMarketplaceAutoBumpRoute: typeof ApiPublicMarketplaceAutoBumpRoute
  ApiPublicMarketplaceFollowupRoute: typeof ApiPublicMarketplaceFollowupRoute
  ApiPublicMarketplaceMatchSearchesRoute: typeof ApiPublicMarketplaceMatchSearchesRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros': {
      id: '/pros'
      path: '/pros'
      fullPath: '/pros'
      preLoaderRoute: typeof ProsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/pros/': {
      id: '/pros/'
      path: '/'
      fullPath: '/pros/'
      preLoaderRoute: typeof ProsIndexRouteImport
      parentRoute: typeof ProsRoute
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/seller/$sellerId': {
      id: '/seller/$sellerId'
      path: '/seller/$sellerId'
      fullPath: '/seller/$sellerId'
      preLoaderRoute: typeof SellerSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros/new': {
      id: '/pros/new'
      path: '/new'
      fullPath: '/pros/new'
      preLoaderRoute: typeof ProsNewRouteImport
      parentRoute: typeof ProsRoute
    }
    '/pros/my-inquiries': {
      id: '/pros/my-inquiries'
      path: '/my-inquiries'
      fullPath: '/pros/my-inquiries'
      preLoaderRoute: typeof ProsMyInquiriesRouteImport
      parentRoute: typeof ProsRoute
    }
    '/pros/$proId': {
      id: '/pros/$proId'
      path: '/$proId'
      fullPath: '/pros/$proId'
      preLoaderRoute: typeof ProsProIdRouteImport
      parentRoute: typeof ProsRoute
    }
    '/marketplace/new': {
      id: '/marketplace/new'
      path: '/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof MarketplaceNewRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/$listingId': {
      id: '/marketplace/$listingId'
      path: '/$listingId'
      fullPath: '/marketplace/$listingId'
      preLoaderRoute: typeof MarketplaceListingIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/academy/podcasts': {
      id: '/academy/podcasts'
      path: '/podcasts'
      fullPath: '/academy/podcasts'
      preLoaderRoute: typeof AcademyPodcastsRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/shop/order/$orderId': {
      id: '/shop/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/shop/order/$orderId'
      preLoaderRoute: typeof ShopOrderOrderIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/pros/$proId/edit': {
      id: '/pros/$proId/edit'
      path: '/edit'
      fullPath: '/pros/$proId/edit'
      preLoaderRoute: typeof ProsProIdEditRouteImport
      parentRoute: typeof ProsProIdRoute
    }
    '/marketplace/category/$slug': {
      id: '/marketplace/category/$slug'
      path: '/category/$slug'
      fullPath: '/marketplace/category/$slug'
      preLoaderRoute: typeof MarketplaceCategorySlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/$listingId/edit': {
      id: '/marketplace/$listingId/edit'
      path: '/edit'
      fullPath: '/marketplace/$listingId/edit'
      preLoaderRoute: typeof MarketplaceListingIdEditRouteImport
      parentRoute: typeof MarketplaceListingIdRoute
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marketplace/match-searches': {
      id: '/api/public/marketplace/match-searches'
      path: '/api/public/marketplace/match-searches'
      fullPath: '/api/public/marketplace/match-searches'
      preLoaderRoute: typeof ApiPublicMarketplaceMatchSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marketplace/followup': {
      id: '/api/public/marketplace/followup'
      path: '/api/public/marketplace/followup'
      fullPath: '/api/public/marketplace/followup'
      preLoaderRoute: typeof ApiPublicMarketplaceFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marketplace/auto-bump': {
      id: '/api/public/marketplace/auto-bump'
      path: '/api/public/marketplace/auto-bump'
      fullPath: '/api/public/marketplace/auto-bump'
      preLoaderRoute: typeof ApiPublicMarketplaceAutoBumpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcademyRouteChildren {
  AcademySlugRoute: typeof AcademySlugRoute
  AcademyPodcastsRoute: typeof AcademyPodcastsRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademySlugRoute: AcademySlugRoute,
  AcademyPodcastsRoute: AcademyPodcastsRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface AdminRouteChildren {
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MarketplaceListingIdRouteChildren {
  MarketplaceListingIdEditRoute: typeof MarketplaceListingIdEditRoute
}

const MarketplaceListingIdRouteChildren: MarketplaceListingIdRouteChildren = {
  MarketplaceListingIdEditRoute: MarketplaceListingIdEditRoute,
}

const MarketplaceListingIdRouteWithChildren =
  MarketplaceListingIdRoute._addFileChildren(MarketplaceListingIdRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceListingIdRoute: typeof MarketplaceListingIdRouteWithChildren
  MarketplaceNewRoute: typeof MarketplaceNewRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceCategorySlugRoute: typeof MarketplaceCategorySlugRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceListingIdRoute: MarketplaceListingIdRouteWithChildren,
  MarketplaceNewRoute: MarketplaceNewRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceCategorySlugRoute: MarketplaceCategorySlugRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface ProsProIdRouteChildren {
  ProsProIdEditRoute: typeof ProsProIdEditRoute
}

const ProsProIdRouteChildren: ProsProIdRouteChildren = {
  ProsProIdEditRoute: ProsProIdEditRoute,
}

const ProsProIdRouteWithChildren = ProsProIdRoute._addFileChildren(
  ProsProIdRouteChildren,
)

interface ProsRouteChildren {
  ProsProIdRoute: typeof ProsProIdRouteWithChildren
  ProsMyInquiriesRoute: typeof ProsMyInquiriesRoute
  ProsNewRoute: typeof ProsNewRoute
  ProsIndexRoute: typeof ProsIndexRoute
}

const ProsRouteChildren: ProsRouteChildren = {
  ProsProIdRoute: ProsProIdRouteWithChildren,
  ProsMyInquiriesRoute: ProsMyInquiriesRoute,
  ProsNewRoute: ProsNewRoute,
  ProsIndexRoute: ProsIndexRoute,
}

const ProsRouteWithChildren = ProsRoute._addFileChildren(ProsRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopOrderOrderIdRoute: typeof ShopOrderOrderIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopOrderOrderIdRoute: ShopOrderOrderIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ForumRoute: ForumRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ProsRoute: ProsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRouteWithChildren,
  ShortsRoute: ShortsRoute,
  StoreRoute: StoreRoute,
  SellerSellerIdRoute: SellerSellerIdRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  ApiPublicMarketplaceAutoBumpRoute: ApiPublicMarketplaceAutoBumpRoute,
  ApiPublicMarketplaceFollowupRoute: ApiPublicMarketplaceFollowupRoute,
  ApiPublicMarketplaceMatchSearchesRoute:
    ApiPublicMarketplaceMatchSearchesRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
